development:
  adapter: postgresql
  encoding: UTF-8
  database: promote_living_development
  host: localhost
  pool: 5
  # username: malachai
  # password:

test:
  adapter: postgresql
  encoding: UTF-8
  database: promote_living_test
  host: localhost
  pool: 5
  # username: malachai
  # password:

# production:
#   adapter: postgresql
#   encoding: UTF-8
#   database: promote_living_production
#   host: localhost
#   pool: 5
#   username: malachai
#   password:
